# spring context variables
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  main:
    banner-mode: off
cron:
  standard: 0 */5 * * * *
logging:
  level:
    root: ERROR
    org.springframework.web: WARN
    inf.awieclawski.sniffer.tsks.ScheduledTasks: WARN
    inf.awieclawski.sniffer.utls.UrlCheck: WARN
    inf.awieclawski.sniffer.rpstr.DataRepository: WARN
    inf.awieclawski.sniffer.schdlrs.TaskSchedulerImpl: WARN
base:
  error:
    msg: Sniffer error handler
# declared dtoList variables
application:
  dtoList:
    -
      sniffedAddress: https://www.baeldung.com
      sniffActive: true
      pathVariables: cron-expressions,java-cron-expressions-wildcards-diff